### ISSUE TITLE
Not converting entire file

### ISSUE THREAD

**Issue by WilliamHosea** [gio54321/bin2fil#10]
This problem just started to occur out of no where, but now when i use bin2fil, it only converts the first few seconds of data then stops. I've tried to convert multiple .bin files, and for each one no more then 18 seconds out of 10800 were converted. I even used files then have been converted before, but they too won't be fully converted.

**Comment by gio54321** [comment]
That's really strange.
Unfortunately I am not able to replicate this behavior.

Could you please give some more information, like:
* have you double-checked all the conversion parameters?
* are you running the latest version?
* when you run the conversion do you see any error in the js developer tools console or in the terminal?

**Comment by WilliamHosea** [comment]
I have discovered what the problem was. After checking that i was using the latest version, I went back through and found out that the USB port i was using was finicky and would randomly disconnect and reconnect. 

Thank you for your help.
